name: Analyze

on:
  push:
  pull_request:

jobs:
  clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install clang-format
        run: |
          sudo apt-get update
          sudo apt-get install clang-format-15

      - name: Verify formatting
        run: |
          FILES=$(git ls-files -- '*.h' '*.cc' '*.cpp' | grep -v /third_party/)
          clang-format-15 --style=file --dry-run --Werror $FILES

  gn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: src

      - name: Install depot_tools
        run: |
          git clone --depth=1 https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "$PWD/depot_tools" >> $GITHUB_PATH

      - name: Run gclient sync
        run: |
          pip3 install requests
          gclient config --name=src --unmanaged https://github.com/${{ github.repository }}
          gclient sync -v --no-history --shallow

      - name: Verify formatting
        working-directory: src
        run: |
          FILES=$(git ls-files -- '*.gn' '*.gni')
          third_party/gn/gn format --dry-run $FILES
